package at.technikum.api;

import at.technikum.api.controller.DocumentController;
import at.technikum.api.exceptions.DocumentNotFoundException;
import at.technikum.api.mapper.DocumentMapperImpl;
import at.technikum.api.service.JwtService;
import at.technikum.api.service.UserService;
import at.technikum.api.service.DocumentService;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.webmvc.test.autoconfigure.WebMvcTest;
import org.springframework.context.annotation.Import;
import org.springframework.security.test.context.support.WithMockUser;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.test.web.servlet.MockMvc;

import java.util.List;
import java.util.UUID;

import static org.mockito.Mockito.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@WebMvcTest(DocumentController.class)
@Import(DocumentMapperImpl.class) //gets generated by mapstruct. TODO: Extract and inject as interface?
@WithMockUser
class DocumentControllerTests {

    @Autowired
    private MockMvc mockMvc;

    @MockitoBean
    private DocumentService documentService;

    @MockitoBean
    private UserService userService;

    @MockitoBean
    private JwtService jwtService;

    @Test
    void get_documents_returns_empty_list() throws Exception {
        when(documentService.findAllDocuments(null)).thenReturn(List.of());

        mockMvc.perform(get("/document"))
                .andExpect(status().isOk())
                .andExpect(content().json("[]"));
    }

    @Test
    void get_documents_passes_search_query_to_service() throws Exception {
        when(documentService.findAllDocuments("invoice")).thenReturn(List.of());

        mockMvc.perform(get("/document").param("query", "invoice"))
                .andExpect(status().isOk())
                .andExpect(content().json("[]"));

        verify(documentService).findAllDocuments("invoice");
    }

    @Test
    void post_document_with_blank_title_returns_bad_request()
            throws Exception {
        mockMvc.perform(post("/document")
                        .contentType("application/json")
                        .content("""
                                {"title": ""}
                                """))
                .andExpect(status().isBadRequest());

        verifyNoInteractions(documentService);
    }

    @Test
    void get_missing_document_returns_not_found() throws Exception {
        UUID missingId = UUID.randomUUID();
        when(documentService.findDocumentById(missingId))
                .thenThrow(new DocumentNotFoundException(missingId));

        mockMvc.perform(get("/document/{documentId}", missingId))
                .andExpect(status().isNotFound())
                .andExpect(jsonPath("$.status").value(404))
                .andExpect(jsonPath("$.error").value("Not Found"))
                .andExpect(jsonPath("$.message").value("Document with ID " + missingId + " was not found."));
    }

    @Test
    void delete_missing_document_returns_not_found() throws Exception {
        UUID missingId = UUID.randomUUID();
        doThrow(new DocumentNotFoundException(missingId)).when(documentService).delete(missingId);

        mockMvc.perform(delete("/document/{documentId}", missingId))
                .andExpect(status().isNotFound())
                .andExpect(jsonPath("$.status").value(404))
                .andExpect(jsonPath("$.error").value("Not Found"))
                .andExpect(jsonPath("$.message").value("Document with ID " + missingId + " was not found."));
    }
}