package at.technikum.api;

import at.technikum.api.controller.DocumentController;
import at.technikum.api.mapper.DocumentMapperImpl;
import at.technikum.api.service.DocumentService;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.webmvc.test.autoconfigure.WebMvcTest;
import org.springframework.context.annotation.Import;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.test.web.servlet.MockMvc;

import java.util.List;

import static org.mockito.Mockito.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@WebMvcTest(DocumentController.class)
@Import(DocumentMapperImpl.class) //gets generated by mapstruct. TODO: Extract and inject as interface?
class DocumentControllerTests {

    @Autowired
    private MockMvc mockMvc;

    @MockitoBean
    private DocumentService documentService;

    @Test
    void get_documents_returns_empty_list() throws Exception {
        when(documentService.findAllDocuments()).thenReturn(List.of());

        mockMvc.perform(get("/document"))
                .andExpect(status().isOk())
                .andExpect(content().json("[]"));
    }

    @Test
    void post_document_with_blank_title_returns_bad_request()
            throws Exception {
        mockMvc.perform(post("/document")
                        .contentType("application/json")
                        .content("""
                                {"title": ""}
                                """))
                .andExpect(status().isBadRequest());

        verifyNoInteractions(documentService);
    }
}