spring.application.name=api

spring.datasource.url=jdbc:postgresql://localhost:5432/paperless
spring.datasource.username=paperless
spring.datasource.password=paperless_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true